package agent

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/yscale-sh/yscale/pkg/protocol"
)

// ArtifactUpload is one staged output directory and the exact object sink
// central authorized for it. KeyPrefix is generated by the connector from the
// immutable workload id and successful pod name; it keeps retry attempts from
// overwriting one another below the customer-selected bucket prefix.
type ArtifactUpload struct {
	LocalPath string             `json:"local_path"`
	KeyPrefix string             `json:"key_prefix"`
	Source    protocol.BucketRef `json:"source"`
	MaxFiles  int                `json:"max_files"`
	MaxBytes  int64              `json:"max_bytes"`
}

type artifactFile struct {
	localPath string
	objectKey string
	size      int64
}

const artifactUploadHTTPTimeout = 10 * time.Minute
const maxArtifactSignerResponseBytes int64 = 4 << 20

// artifactTerminationMessagePath is where the kubelet reads a container's
// termination message from, and where the uploader leaves its summary.
const artifactTerminationMessagePath = "/dev/termination-log"

// maxArtifactSummaryBytes bounds what the watcher will even attempt to parse.
// The kubelet truncates a termination message to 4 KiB, so anything longer did
// not come from the path this reads.
const maxArtifactSummaryBytes = 4096

// ArtifactUploadResult is what an upload actually completed. It is returned
// even when the upload fails part-way: three of five objects uploaded is the
// honest half of a failed export, and the receipt carries it.
type ArtifactUploadResult struct {
	ObjectsUploaded int64
	BytesUploaded   int64
}

// artifactUploadSummary is the strict JSON the uploader writes to its
// termination message on every exit, and the only thing the completion watcher
// will believe about counts. Reason is a closed category token (one of the
// artifactFailure* constants), not free text: the watcher maps it to a fixed
// phrase, so nothing the uploader saw — an object key, a signed URL, an
// endpoint, a server response body — can reach a durable record through it.
type artifactUploadSummary struct {
	Result          string `json:"result"`
	Reason          string `json:"reason,omitempty"`
	ObjectsUploaded int64  `json:"objects_uploaded"`
	BytesUploaded   int64  `json:"bytes_uploaded"`
}

// artifactUploadError tags a failure with the category token its summary
// carries. Only the token travels; the wrapped error is for the uploader's own
// logs and exit code.
type artifactUploadError struct {
	category string
	err      error
}

func (e *artifactUploadError) Error() string { return e.err.Error() }
func (e *artifactUploadError) Unwrap() error { return e.err }

func artifactFailure(category string, err error) error {
	return &artifactUploadError{category: category, err: err}
}

func artifactFailuref(category, format string, args ...any) error {
	return &artifactUploadError{category: category, err: fmt.Errorf(format, args...)}
}

// artifactFailureCategory reports which category an upload failure belongs to.
// An untagged error yields no category, which the watcher renders as the
// generic phrase rather than guessing.
func artifactFailureCategory(err error) string {
	var tagged *artifactUploadError
	if errors.As(err, &tagged) {
		return tagged.category
	}
	return ""
}

// RunArtifactUploadCommand is the `artifact-upload` entrypoint the uploader Job
// runs. Whatever happens it leaves a summary behind: the completion watcher
// reads it back to put honest counts on the workload's receipt.
func RunArtifactUploadCommand(ctx context.Context, uploadsJSON, endpoint, burstID string) error {
	return runArtifactUploadCommand(ctx, artifactTerminationMessagePath, uploadsJSON, endpoint, burstID)
}

func runArtifactUploadCommand(ctx context.Context, summaryPath, uploadsJSON, endpoint, burstID string) error {
	result, err := uploadsFromJSON(ctx, uploadsJSON, endpoint, burstID)
	writeArtifactUploadSummary(summaryPath, result, err)
	return err
}

func uploadsFromJSON(ctx context.Context, uploadsJSON, endpoint, burstID string) (ArtifactUploadResult, error) {
	var uploads []ArtifactUpload
	if err := json.Unmarshal([]byte(uploadsJSON), &uploads); err != nil {
		return ArtifactUploadResult{}, artifactFailuref(artifactFailureConfiguration, "decode YSCALE_ARTIFACT_UPLOADS: %w", err)
	}
	return RunArtifactUploader(ctx, endpoint, burstID, uploads)
}

// writeArtifactUploadSummary records what the upload completed where the
// watcher can read it back. Best-effort by design: a summary the kubelet never
// surfaces costs the receipt its counts, and must not cost the uploader its
// exit code.
func writeArtifactUploadSummary(path string, result ArtifactUploadResult, uploadErr error) {
	summary := artifactUploadSummary{
		Result:          OutcomeResultSucceeded,
		ObjectsUploaded: result.ObjectsUploaded,
		BytesUploaded:   result.BytesUploaded,
	}
	if uploadErr != nil {
		summary.Result = OutcomeResultFailed
		summary.Reason = artifactFailureCategory(uploadErr)
	}
	encoded, err := json.Marshal(summary)
	if err != nil || len(encoded) > maxArtifactSummaryBytes {
		return
	}
	_ = os.WriteFile(path, encoded, 0o644)
}

// parseArtifactUploadSummary decodes a termination message into a summary, or
// reports that it is not one. Bounded, exactly one JSON value, no unknown
// fields, closed result vocabulary, no negative counts: a message that fails
// any of those is not a summary this uploader wrote, and the caller falls back
// to the Job's own verdict with no counts.
func parseArtifactUploadSummary(message string) (artifactUploadSummary, bool) {
	if message == "" || len(message) > maxArtifactSummaryBytes {
		return artifactUploadSummary{}, false
	}
	var out artifactUploadSummary
	dec := json.NewDecoder(strings.NewReader(message))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&out); err != nil {
		return artifactUploadSummary{}, false
	}
	if err := dec.Decode(&struct{}{}); err != io.EOF {
		return artifactUploadSummary{}, false
	}
	switch out.Result {
	case OutcomeResultSucceeded, OutcomeResultFailed:
	default:
		return artifactUploadSummary{}, false
	}
	if out.ObjectsUploaded < 0 || out.BytesUploaded < 0 {
		return artifactUploadSummary{}, false
	}
	return out, true
}

// RunArtifactUploader uploads all regular files from the staged directories.
// It never receives bucket credentials: the agent-side signer exchanges the
// burst grant for short-lived PUT URLs scoped to the exact authorized sink.
//
// The counts it returns are what it completed, not what it set out to do, so a
// failure part-way still reports the objects that reached the bucket.
func RunArtifactUploader(ctx context.Context, endpoint, burstID string, uploads []ArtifactUpload) (ArtifactUploadResult, error) {
	return runArtifactUploader(ctx, endpoint, burstID, uploads, &http.Client{Timeout: artifactUploadHTTPTimeout})
}

func runArtifactUploader(ctx context.Context, endpoint, burstID string, uploads []ArtifactUpload, client *http.Client) (ArtifactUploadResult, error) {
	var result ArtifactUploadResult
	if burstID == "" {
		return result, artifactFailuref(artifactFailureConfiguration, "BURST_ID is required")
	}
	signURL, err := artifactSignURL(endpoint)
	if err != nil {
		return result, artifactFailure(artifactFailureConfiguration, err)
	}
	if len(uploads) == 0 {
		return result, artifactFailuref(artifactFailureConfiguration, "at least one artifact upload is required")
	}
	for i, upload := range uploads {
		files, err := collectArtifactFiles(upload)
		if err != nil {
			return result, artifactFailuref(artifactFailureConfiguration, "artifact %d: %w", i, err)
		}
		if len(files) == 0 {
			continue
		}
		objects := make([]string, 0, len(files))
		byObject := make(map[string]artifactFile, len(files))
		for _, file := range files {
			objects = append(objects, file.objectKey)
			byObject[file.objectKey] = file
		}
		signed, err := requestArtifactURLs(ctx, client, signURL, burstID, upload.Source, objects)
		if err != nil {
			return result, artifactFailuref(artifactFailureSigner, "artifact %d sign: %w", i, err)
		}
		if len(signed) != len(files) {
			return result, artifactFailuref(artifactFailureSigner, "artifact %d signer returned %d URLs for %d files", i, len(signed), len(files))
		}
		seen := make(map[string]struct{}, len(signed))
		for _, object := range signed {
			file, ok := byObject[object.Key]
			if !ok {
				return result, artifactFailuref(artifactFailureSigner, "artifact %d signer returned an unrequested object key", i)
			}
			if _, duplicate := seen[object.Key]; duplicate {
				return result, artifactFailuref(artifactFailureSigner, "artifact %d signer returned a duplicate object key", i)
			}
			seen[object.Key] = struct{}{}
			if err := putArtifactFile(ctx, client, object.URL, file); err != nil {
				return result, artifactFailuref(artifactFailureUpload, "artifact %d upload %q: %w", i, object.Key, err)
			}
			// Counted only here — putArtifactFile returns nil for a 2xx and
			// nothing else, so a retried attempt that never succeeded cannot
			// add to a count the customer reads back.
			result.ObjectsUploaded++
			result.BytesUploaded += file.size
		}
	}
	return result, nil
}

func artifactSignURL(endpoint string) (string, error) {
	parsed, err := url.Parse(endpoint)
	if err != nil || parsed.Host == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") {
		return "", fmt.Errorf("BOOTSTRAP_ENDPOINT must be an http(s) origin")
	}
	if parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" || (parsed.Path != "" && parsed.Path != "/") {
		return "", fmt.Errorf("BOOTSTRAP_ENDPOINT must not contain credentials, a path, query, or fragment")
	}
	parsed.Path = "/storage/sign-urls"
	return parsed.String(), nil
}

func collectArtifactFiles(upload ArtifactUpload) ([]artifactFile, error) {
	if upload.MaxFiles < 1 || upload.MaxFiles > maxSignedObjects {
		return nil, fmt.Errorf("max_files must be between 1 and %d", maxSignedObjects)
	}
	if upload.MaxBytes < 1 {
		return nil, fmt.Errorf("max_bytes must be positive")
	}
	if !validRelativeObjectKey(upload.KeyPrefix) {
		return nil, fmt.Errorf("key_prefix is not a canonical relative key")
	}
	root, err := filepath.Abs(upload.LocalPath)
	if err != nil {
		return nil, fmt.Errorf("resolve local path: %w", err)
	}
	rootInfo, err := os.Lstat(root)
	if err != nil {
		return nil, fmt.Errorf("inspect local path: %w", err)
	}
	if !rootInfo.IsDir() || rootInfo.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("local path must be a real directory")
	}

	files := make([]artifactFile, 0)
	var total int64
	err = filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == root {
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("symlink outputs are not allowed")
		}
		if entry.IsDir() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("non-regular output files are not allowed")
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		key := strings.TrimSuffix(upload.KeyPrefix, "/") + "/" + rel
		if !validRelativeObjectKey(rel) || !validRelativeObjectKey(key) {
			return fmt.Errorf("output path is not a canonical relative object key")
		}
		if len(files) >= upload.MaxFiles {
			return fmt.Errorf("output exceeds the %d-file limit", upload.MaxFiles)
		}
		if info.Size() > upload.MaxBytes-total {
			return fmt.Errorf("output exceeds the %d-byte limit", upload.MaxBytes)
		}
		total += info.Size()
		files = append(files, artifactFile{localPath: path, objectKey: key, size: info.Size()})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].objectKey < files[j].objectKey })
	return files, nil
}

func requestArtifactURLs(ctx context.Context, client *http.Client, endpoint, burstID string, source protocol.BucketRef, objects []string) ([]SignedURL, error) {
	body, err := json.Marshal(SignURLsRequest{BurstID: burstID, Mode: "write", Source: source, Objects: objects})
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		detail, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return nil, fmt.Errorf("signer returned HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(detail)))
	}
	var signed SignURLsResponse
	decoder := json.NewDecoder(io.LimitReader(resp.Body, maxArtifactSignerResponseBytes))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&signed); err != nil {
		return nil, fmt.Errorf("decode signer response: %w", err)
	}
	return signed.URLs, nil
}

func putArtifactFile(ctx context.Context, client *http.Client, signedURL string, file artifactFile) error {
	parsed, err := url.Parse(signedURL)
	if err != nil || parsed.Host == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.User != nil {
		return fmt.Errorf("signer returned an invalid upload URL")
	}
	var lastErr error
	for attempt := 0; attempt < 3; attempt++ {
		if attempt > 0 {
			timer := time.NewTimer(time.Duration(1<<uint(attempt-1)) * time.Second)
			select {
			case <-ctx.Done():
				timer.Stop()
				return ctx.Err()
			case <-timer.C:
			}
		}
		input, err := os.Open(file.localPath)
		if err != nil {
			return err
		}
		req, err := http.NewRequestWithContext(ctx, http.MethodPut, signedURL, input)
		if err != nil {
			input.Close()
			return err
		}
		req.ContentLength = file.size
		resp, err := client.Do(req)
		input.Close()
		if err == nil {
			_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 4096))
			resp.Body.Close()
			if resp.StatusCode >= 200 && resp.StatusCode < 300 {
				return nil
			}
			if resp.StatusCode < 500 && resp.StatusCode != http.StatusTooManyRequests {
				return fmt.Errorf("object store returned HTTP %d", resp.StatusCode)
			}
			lastErr = fmt.Errorf("object store returned HTTP %d", resp.StatusCode)
			continue
		}
		lastErr = err
	}
	return lastErr
}
