{{- if not .Values.secrets.existingSecret }}
{{- if or .Values.secrets.flyioToken .Values.secrets.tsAuthKey .Values.secrets.k3sToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yscale.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "yscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.flyioToken }}
  FLYIO_TOKEN: {{ .Values.secrets.flyioToken | quote }}
  {{- end }}
  {{- if .Values.secrets.tsAuthKey }}
  TS_AUTHKEY: {{ .Values.secrets.tsAuthKey | quote }}
  {{- end }}
  {{- if .Values.secrets.k3sToken }}
  K3S_TOKEN: {{ .Values.secrets.k3sToken | quote }}
  {{- end }}
{{- end }}
{{- end }}
