package main

import (
	"encoding/base64"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"k8s.io/client-go/tools/clientcmd"
)

// runInit implements `yscale init`: extract apiServer + clusterCA from a
// kubeconfig and emit a Helm values fragment so the user doesn't have to
// hand-extract the CA, paste it in base64, and copy the API server URL.
//
// Usage:
//
//	yscale init --kubeconfig ~/.kube/config > values.yaml
//	yscale init --context production > values.yaml
//
// The output is a Helm values fragment for join.{apiServer,clusterCA} only.
// Backend, Tailscale, and Scaling settings are left for the user to fill
// in — they are deployment decisions yscale can't infer from a kubeconfig.
func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)

	var (
		kubeconfig  string
		contextName string
	)
	fs.StringVar(&kubeconfig, "kubeconfig", "", "path to kubeconfig (defaults to $KUBECONFIG, then ~/.kube/config)")
	fs.StringVar(&contextName, "context", "", "context to use from kubeconfig (defaults to current-context)")

	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}

	if kubeconfig == "" {
		kubeconfig = os.Getenv("KUBECONFIG")
	}
	if kubeconfig == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("locating home dir: %w", err)
		}
		kubeconfig = filepath.Join(home, ".kube", "config")
	}

	cfg, err := clientcmd.LoadFromFile(kubeconfig)
	if err != nil {
		return fmt.Errorf("loading kubeconfig %s: %w", kubeconfig, err)
	}

	if contextName == "" {
		contextName = cfg.CurrentContext
	}
	if contextName == "" {
		return fmt.Errorf("no context specified and kubeconfig has no current-context")
	}

	kctx, ok := cfg.Contexts[contextName]
	if !ok {
		return fmt.Errorf("context %q not found in kubeconfig", contextName)
	}
	cluster, ok := cfg.Clusters[kctx.Cluster]
	if !ok {
		return fmt.Errorf("cluster %q (referenced by context %q) not found in kubeconfig", kctx.Cluster, contextName)
	}
	if cluster.Server == "" {
		return fmt.Errorf("cluster %q has no server URL", kctx.Cluster)
	}

	// CA: prefer inline CertificateAuthorityData; fall back to file path.
	caData := cluster.CertificateAuthorityData
	if len(caData) == 0 && cluster.CertificateAuthority != "" {
		caData, err = os.ReadFile(cluster.CertificateAuthority)
		if err != nil {
			return fmt.Errorf("reading cluster CA file %s: %w", cluster.CertificateAuthority, err)
		}
	}
	if len(caData) == 0 {
		return fmt.Errorf("no cluster CA found for cluster %q (kubeconfig had neither certificate-authority-data nor certificate-authority)", kctx.Cluster)
	}
	caB64 := base64.StdEncoding.EncodeToString(caData)

	out := fmt.Sprintf(`# Generated by 'yscale init' from kubeconfig context %q.
# Merge into your Helm values file (e.g. deploy/helm/yscale/values.yaml).
#
# Verify with:
#   helm upgrade --install yscale ./deploy/helm/yscale \
#     -n kube-system --create-namespace -f values.yaml

join:
  mode: kubelet
  apiServer: %q
  clusterCA: %q

# --- still up to you ---
#
# backend:
#   type: flyio
#   flyio:
#     org: personal
#     region: ord
#
# tailscale:
#   enabled: false        # set true if your apiServer is private (homelab, internal LB)
#
# secrets:
#   flyToken: ""          # required when backend.type=flyio
#   tsAuthKey: ""         # required when tailscale.enabled=true
#
# scaling:
#   maxNodes: 10
#   maxMonthlyUSD: 50     # hard cap on accrued spend per calendar month
`, contextName, cluster.Server, caB64)

	_, err = io.WriteString(os.Stdout, out)
	return err
}
